### ISSUE TITLE
"Not secure" according to Chrome

### ISSUE THREAD

**Issue by JMeth1** [KLVN/MediasiteDownloader#1]
First of all: Thanks a million for sharing your Bookmarklet. 

Unfortunately it's not working for me. When I click the bookmarklet while playing the video the https protocol blocks it for being "not secure". 

Is it supposed to work for students like myself that need to login first to be able to open the lectures? Or does it only work with public ones? 

Thanks.

**Comment by KLVN** [comment]
Hi @JMeth1,

what university are you studying at? I just noticed that I made a mistake while programming and therefore it only works for students of the TUHH (Germany). I will fix it ASAP. After that you'll be able to download private and public lectures.

Thanks for reporting this problem!

**Comment by KLVN** [comment]
Should be fixed now. I tested it with [this lecture](https://lecture.ucanr.edu/Mediasite/Play/11e1dd9bf97542b3a5d6cd992407e1371d) and besides the ugly dialog window it works. Seems like my university is using an older version of _Mediasite_ and handles things differently - maybe I'll revamp the dialog for all versions 🤔
