### ISSUE TITLE
TypeError with the extension

### ISSUE THREAD

**Issue by kdqdev** [KLVN/MediasiteDownloader#10]
I am receiving VM12219:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'PlayStatus')

**Comment by KLVN** [comment]
Do you have a link to the lecture?

**Comment by kdqdev** [comment]
The lecture is protected and can't be accessed by people outside the organization. The extension is working now for some reason. You can close the issue now. Thank you for the quick response.
