### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by lebohnes** [KLVN/MediasiteDownloader#4]
hallo together,

i'm getting a 404 error if i use ur script as described. I found out that it only works if i replace in the resulting url 'SmoothStreaming' with 'MediasiteDeliver'. 

greets

**Comment by KLVN** [comment]
Hi,
is the Mediasite lecture public, so that I can take a look at it? This script only searches for the source-URLs of the video files and I never came across "SmoothStreaming" (at least in my Mediasite lectures).


(Btw, do you speak German?)

**Comment by lebohnes** [comment]
Ja ich spreche deutsch.

Also nein, die Vorlesung ist nicht öffentlich. 

Ich bin folgender Anleitung gefolgt:
https://www.reddit.com/r/DataHoarder/comments/8h9kfg/downloading_a_lecture_from_mediasitecom/

und habe es anschließend mit dem Link von deinem Script verglichen.

**Comment by KLVN** [comment]
Danke für den Link. Dieses Skript funktioniert nur bei Videos, die im MP4-Format als einzelne Datei vorliegen. Dash und Silverlight werden nicht unterstützt, weil diese immer nur "häppchenweise" vorliegen und man mit so einem einfachen JavaScript-Lesezeichen nicht alle einzelnen Fragmente zusammenfügen kann. Von den 4 genannten Aufzeichnungen im reddit-Post kann ich mit dem Skript 2 davon herunterladen - die anderen beiden liegen nicht als MP4 vor. Auch dort konnte ich keine URL mit "SmoothStreaming" finden, die dann mit "MediasiteDeliver" funktionieren würde.

Aber ich konnte zum ersten Mal den Parameter "VodcastUrl" sehen, hinter dem sich eine MP4-Datei verbirgt, die sogar Kameraaufnahme und Foliensatz vereint. Das werde ich in der nächsten Version noch implementieren. Leider unterstützt/benutzt meine Uni nicht diese Funktion und auch MP4 wird eher selten benutzt. Wie sieht es bei dir aus, wenn du in der "GetPlayerOptions" Response nach "VodcastUrl" suchst?
