### ISSUE TITLE
Only Video Feed no slides

### ISSUE THREAD

**Issue by p3l4h0** [KLVN/MediasiteDownloader#5]
unfortunately I only get the video feed downloaded. The displayed parallel slides are not saved.

**Comment by KLVN** [comment]
Only video files are supported. Unfortunately, slides are often uploaded as a slideshow with literally hundreds of images, that are just screenshots of the slides, taken every few seconds. These can't be converted into a video file with such a simple JavaScript-Bookmarklet.

**Comment by p3l4h0** [comment]
a pity, but thanks for the tool and the quick answer

**Comment by KLVN** [comment]
I've added support for downloading "Vodcasts". These are video files that combine different sources, like cameras **and** slides. Vodcasts are pretty rare, but maybe you have some luck.

Here's an example for a Mediasite lecture with Vodcast enabled. A click on the thumbnail (in this specific case it's just black. Not my fault ;) ) will immediately start the download and even rename the file correctly: https://events7.mediasite.com/Mediasite/Play/aa2bda227c11494295a41bbc3c2058141d

**Comment by p3l4h0** [comment]
There it is working, but i have tried it in this source.
Not sure if this is a Vodcast:
http://webcast.tuhh.de/Mediasite/Play/3edddda5db1e4665bde716052b05358b1d#

**Comment by KLVN** [comment]
Sadly not. Vodcasts will be displayed by the script like this: 
![image](https://user-images.githubusercontent.com/8047980/80309395-16e34b80-87d5-11ea-988c-3b8deee0ecd3.png)
