### ISSUE TITLE
Nothing when pressing bookmark

### ISSUE THREAD

**Issue by reinharto** [KLVN/MediasiteDownloader#6]
I got this in the console using Chrome. https://puu.sh/H9lnH/35efd95ab1.png

**Comment by KLVN** [comment]
Thanks for opening the issue, I'll look into it!
I've never seen this kind of implementation/embedding of Mediasite before, but I already found [something similar and openly available](https://fau.mediasite.com/Mediasite/channel/4326ff870f48400db33f32bc725692785f/watch/7c1247bb1e1c40b88f0653f55b8ad3c31d) that looks just like your screenshot.

**Comment by KLVN** [comment]
Dirty and manual workaround if it's urgent:
- Right-click on Mediasite lecture -> View frame source
- Look for `var url = "..."` and open in new tab, like this
![image](https://user-images.githubusercontent.com/8047980/105473656-a1da6f00-5c9d-11eb-901c-65b0e3543366.png)
- Click on Mediasite Downloader bookmark

I'll still try implementing it ;)
