### ISSUE TITLE
mediasite does not support jQuery

### ISSUE THREAD

**Issue by alex-de-zwart** [KLVN/MediasiteDownloader#8]
Mediasite does not support jQuery, so the API call cannot be done

<img width="894" alt="jquery" src="https://user-images.githubusercontent.com/61537052/182090883-832a2cc7-42a8-455d-a08d-6489daf6aa84.PNG">

**Comment by KLVN** [comment]
Thanks for reporting. Is this lecture available to everyone or login protected? Do you use extensions that may block the loading 
 of jQuery?

**Comment by alex-de-zwart** [comment]
Thanks for the prompt response; this is a login-protected lecture. A couple of weeks ago, I was able to download the classes. But since this week, I receive the jQuery error. I use chrome without any extension.
