### ISSUE TITLE
Mediasite has updated their webplayer. This no longer works, will there be a fix?!

### ISSUE THREAD

**Issue by petenstuff** [KLVN/MediasiteDownloader#9]
Mediasite has updated the web player, the Mediasite DL bookmark no longer works. Are you aware of this? If so, will you be bringing out a new updated version that supports the new player?

Many thanks!

**Comment by KLVN** [comment]
Thanks for reporting. I'd have to find a public Mediasite lecture first that uses the latest player, because my university is still running an older version (that is still working with this download script). Any chance that your lecture is openly available so I can check it out?
Please be advised that I can give no guarantees, in case Mediasite changed something significantly and made it more secure.

**Comment by byronetodd** [comment]
> Thanks for reporting. I'd have to find a public Mediasite lecture first that uses the latest player, because my university is still running an older version (that is still working with this download script). Any chance that your lecture is openly available so I can check it out? Please be advised that I can give no guarantees, in case Mediasite changed something significantly and made it more secure.

Hi, Thanks for the app. 
Here is a lecture from my university. Pretty sure it is public.

I would be grateful if you could help figure out how to run this on the new mediasite.

**Comment by KLVN** [comment]
Thanks @byronetodd, I can access the lecture. After a quick look it seems like it is related to #8.

Btw, I'll also fix your issue #7.

**Comment by byronetodd** [comment]
> Thanks @byronetodd, I can access the lecture. After a quick look it seems like it is related to #8.
> 
> Btw, I'll also fix your issue #7.

Awesome, thank you for your help! This project has been a godsend with the unreliable server my school uses.

**Comment by KLVN** [comment]
Hey guys, after fiddling around I was able to make the script work again on the latest version of Mediasite players 🎉 This is still a work in progress because now it doesn't work with the older versions anymore :D

In case you can't wait any longer and need this ASAP, do a right-click on the bookmark, then "Edit..." and paste the following code into the "URL" field:

```js
javascript:(function(){document.getElementById("player-iframe")&&(alert('MediasiteDownloader: A Mediasite Channel was detected. After you click "OK" you will be redirected to the video. Click Play and then again on the MediasiteDownloader bookmark.\nNote: Your browser may block the redirect. Make sure to allow pop-ups for this website.'),window.open(document.getElementById("player-iframe").src)),fetch(window.location.origin+SiteData.PlayerService+"/GetPlayerOptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({getPlayerOptionsRequest:{ResourceId:SiteData.PresentationId,QueryString:"",UseScreenReader:"false",UrlReferrer:""}})}).then(a=>a.json()).then(c=>{if(document.head.insertAdjacentHTML("beforeend","<style type='text/css'>.modal-window {position: fixed;display: flex;justify-content: center;align-items: center;background-color: rgba(0, 0, 0, 0.75);top: 0;right: 0;bottom: 0;left: 0;z-index: 999;opacity: 0;pointer-events: none;}.modal-window:target {opacity: 1;pointer-events: auto;}.modal-window > div {width: 450px;position: absolute;padding: 3em;background: #ffffff;color: #333333;border-radius: 5px;}.modal-window header {font-weight: bold;}.modal-window h1 {font-size: 150%;margin: 0 0 15px;color: #333333;}.modal-close {color: #4c4c4c;line-height: 35px;position: absolute;right: 5px;text-align: center;top: 5px;width: 70px;text-decoration: none;border: #4c4c4c;border-style: solid;border-radius: 5px;border-width: 1px;}.modal-window > div > ul > li {margin: 10px 0;}.MSDLthumbnail {width: 350px;vertical-align: middle;margin-bottom: 4px;}div#MSDLinfo {max-height: 70vh;min-height: 5vh;overflow-y: auto;}</style>"),document.contains(document.getElementById("open-modal"))&&document.getElementById("open-modal").remove(),"OnDemand"!=c.d.Presentation.PlayStatus)document.body.insertAdjacentHTML("beforeend",'<div id="open-modal" class="modal-window"><div><a href="#" title="Close" class="modal-close">Close</a><p style="font-size: 20px;">Lecture is currently not available on-demand and therefore cannot be downloaded.<br>Try again later.</p></div></div>');else{document.body.insertAdjacentHTML("beforeend",'<div id="open-modal" class="modal-window"><div><div style="font-size: 20px;line-height: 45px;position: absolute;left: 20px;top: 5px;">MediasiteDownloader (<a href="https://github.com/KLVN/MediasiteDownloader" target="_blank">GitHub</a>)</div><a href="#" title="Close" class="modal-close">Close</a><div id="MSDLinfo"><ul style="list-style: outside; !important"><li>Copy the title: <input type="text" onClick="this.select();" value="'+document.title+'"></li><li>Right-click on the thumbnail(s) and choose "Save <span style="font-weight: bold;">link</span> as..."</li><div id="MSDLvideos"></div><li>Paste in to rename file correctly and save it</li><li>Click <a href="https://klvn.github.io/MediasiteDownloader/" target="_blank">here</a> for more detailed instructions</li></ul></div></div></div>');for(var b=c.d.Presentation.Streams,e=!1,a=0;a<b.length;a++)if(b[a].VideoUrls.length){for(var d=0;d<b[a].VideoUrls.length;d++)if("video/mp4"==b[a].VideoUrls[d].MimeType){e=!0;var f=window.location.origin+b[a].ThumbnailUrl,g=b[a].VideoUrls[d].Location;document.getElementById("MSDLvideos").innerHTML+="<li><a href='"+g+"' target='_blank'><img class='MSDLthumbnail' src='"+f+"'></a></li>"}}if(null!=c.d.Presentation.VodcastUrl){e=!0;var f=window.location.origin+c.d.Presentation.ThumbnailUrl,g=c.d.Presentation.VodcastUrl;document.getElementById("MSDLvideos").innerHTML+="<li>Vodcast:<br><a href='"+g+"' target='_blank'><img class='MSDLthumbnail' src='"+f+"'></a></li>"}e||(document.getElementById("MSDLinfo").innerHTML="<li>Sorry, no video(s) available.</li>")}MediasitePlayer.pause(),location.href="#open-modal"})})()
```

Next, I have to merge both code bases into a single file again and then I will notify you in this issue when it's done.

Here's a screenshot of the current implementation that has not been pushed to GitHub yet (looks a bit weird, but it works):
![image](https://user-images.githubusercontent.com/8047980/186270854-fc393b60-1f4e-46fb-9258-27ca4f4ab575.png)

**Comment by KLVN** [comment]
Ok, I couldn't resist so I quickly hacked together both code bases to support old **and** new Mediasite versions in a single script 👏🏼 I made sure that it works with the lecture from @byronetodd and [this old Mediasite demo](https://events7.mediasite.com/Mediasite/Play/1fae82e4810b4b0ea4d7b78503ebcab41d).

Next up is #7 and after that I'll clean up all of the code to make it a bit smaller again.
